version: "3.9"
name: "weather-pi"
services:
  influxdb:
    image: "influxdb:2.7.1-alpine"
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: MyPassword
      DOCKER_INFLUXDB_INIT_ORG: dev
      DOCKER_INFLUXDB_INIT_BUCKET: weatherpi
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: 5evDxwgsVR610NBJOiGZux05J1Z7-Ilem9k5s3T_ufsZ7DbUYVn8lEXIRoWP8jttApfi5MYUknH9rWXUNSvFsg==